### ISSUE TITLE
Modrinth Support

### ISSUE THREAD

**Issue by ExoPlant** [jaredlll08/Controlling#104]

**Comment by jaredlll08** [comment]
I am happy with my mods on CurseForge right now.

**Comment by ExoPlant** [comment]
Why not have it on modrinth? I don't see any reason not to have it on modrinth

**Comment by jaredlll08** [comment]
Partly because I refuse to support platforms where users literally have to spam authors telling them to use it.

If modrinth was so good, I would want to support it myself, not because I got spammed with issues from a user telling me to support it.

You also need to understand, modding is my job, I spend ***a lot*** of time making mods and providing support for this community.

While modrinth does show ads, they currently do not give **anything** back to authors (as said by their main page), you are asking me to sacrifice my earnings to support a platform that hasn't exactly prioritised monetisation for authors and doesn't offer me anything.

When I was making a CurseForge [competitor ](https://github.com/diluv), we didn't want any community projects using it until we could offer authors the monetisation that they deserved, and modrinth not doing similar does not exactly instil me with confidence for the platform.

Also to be clear, I am not saying that modrinth shouldn't earn anything from this, they obviously need funds to run the platform and pay for developers, I am more commenting on the fact that they have been in beta for about a year and still don't have a solution.

**Comment by jaredlll08** [comment]
https://modrinth.com/user/jaredlll08
