### ISSUE TITLE
[1.12.2] 3.0.12.2 Don't show key categories

### ISSUE THREAD

**Issue by mczph** [jaredlll08/Controlling#154]
3.0.10
![image](https://github.com/jaredlll08/Controlling/assets/103164772/37a6ac56-58e6-44c5-8b82-0516262a84ab)

3.0.12.2
![image](https://github.com/jaredlll08/Controlling/assets/103164772/a418e8f5-0ec2-49a2-bdc9-55df0d519284)

I really like the free keys feature,but this bug is kind of annoying.

**Comment by jaredlll08** [comment]
Just to confirm, is the category not showing on the new versions when you hover over the category? you mouse isn't in the picture so it's a bit hard to see

**Comment by mczph** [comment]
Yes.

**Comment by mczph** [comment]
@jaredlll08 hi, how is the fix going (just a reminder, ignore if you have more important things to do)

**Comment by jaredlll08** [comment]
1.12 is extremely far down on my priority list, it will be resolved when it is resolved.

**Comment by xJon** [comment]
In `3.0.12.2` and above, it shows _only_ when hovering over a *very specific sliver* per key:
![image](https://github.com/jaredlll08/Controlling/assets/8945347/17836b6b-5de9-407b-bcbb-f46090633cfb)

I assume that @kappa-maintainer's https://github.com/jaredlll08/Controlling/pull/133 caused this regression.

It'd be great to fix this because it's highly useful when searching for keybinds and wanting to know which mod they are from, e.g. a player searched for "Vein Miner" and only thanks to the category name they could tell it was from Modular Powersuits.

**Comment by xJon** [comment]
Thank you @kappa-maintainer for the fix 🎉
