### ISSUE TITLE
Screen cut off

### ISSUE THREAD

**Issue by Colton-Slayden** [jaredlll08/Controlling#40]
when in the settings the screen is cut off on the left. 
![minecraft_broken](https://user-images.githubusercontent.com/32550284/63817306-60576000-c901-11e9-88c4-8b467f57d461.png)

**Comment by jaredlll08** [comment]
What gui scale?

**Comment by jaredlll08** [comment]
I have never been able to reproduce this, I really do think it is some weird MC bug that comes and goes, try resizing the window and then maximizing it again, may fix it, but I don't have code to fix this unfortunately

**Comment by nermalneedscoffee** [comment]
This issue still persists and I doubt it is due to an MC bug. I think it has to do with the fact that with controlling, the name of the control and buttons are skewed to the left far too much. This can be seen in the fact that when using different gui scales, the buttons and the names are not centered as they should be. This bug does not occur on 1.14 versions, but seems to be consistent throughout the more recent 1.12.2 versions.

**Comment by scribbler957** [comment]
I've seen it many times too.
