### ISSUE TITLE
UnsupportedOperationException: The BROWSE action is not supported on the current platform!

### ISSUE THREAD

**Issue by drunderscore** [jaredlll08/Controlling#78]
Clicking the `Patreon` button on my Linux machine throws this exception. You should probably:
- Check if the platform actually has `Desktop` support, and `Desktop.Action.BROWSE` support.
- Not be calling `Desktop.browse` directly, but instead show the default Minecraft URL GUI.

Output from `uname`:
```
$ uname
Linux JAMES-DESKTOP 5.8.0-44-generic #50-Ubuntu SMP Tue Feb 9 06:29:41 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jaredlll08** [comment]
So last I checked, I'm using the exact same code that the Minecraft URL GUI uses, so that would crash on your system as well.

I am going to move to use the URL GUI however as I think that would be cool and it gives people the option to copy it.

Unfortunately I don't think that would fix your issue.
