### ISSUE TITLE
Move the reset button please

### ISSUE THREAD

**Issue by ChromaPIE** [jaredlll08/Controlling#85]
The Reset button was unfortunately put at the place where in most of other GUIs is the Done button, causing me getting closer to finally smash my keyboard into pieces when everything I've carefully set to be reverted.

At least make it requiring an additional confirmation.

I do noticed that there was a resolved issue requesting for a confirm, but it didn't seem to work on my end.

**Comment by jaredlll08** [comment]
Well, firstly the button is in the exact place that it is in the vanilla GUI, I never moved it.

Secondly looking at the vanilla GUIs like the Language and Resource Packs GUIs, their "done" button is on the right, exactly how it is in the controls GUI.

and lastly as you pointed out, there is a confirmation before resetting your keys, it has existed since *at least* 1.14 (since I used a 1.14 environment to confirm that right now), so not sure what version you are using, but on my side it is working fine.

**Comment by ChromaPIE** [comment]
Well It's 1.12.2. I'd be okay with it if the mod for that version wouldn't be updated anymore.
